# Generated by Django 3.2.13 on 2022-04-25 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('cash', models.CharField(default='0', max_length=250)),
                ('card_limit', models.CharField(default='-1', max_length=250)),
                ('loan', models.CharField(default='-1', max_length=250)),
                ('due', models.CharField(default='-1', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cash_transaction', models.FloatField(default='0.0')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.finance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
