# Generated by Django 3.2.13 on 2022-04-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_finance_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='card_limit',
            field=models.FloatField(default='-1'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='cash',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='due',
            field=models.FloatField(default='-1'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='loan',
            field=models.FloatField(default='-1'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
